### ISSUE TITLE
Slack link on website does not work

### ISSUE THREAD

**Issue by Jacalz** [nlug/nlug.github.io#4]
I tried to click the slack link on my phone, but I just get an error that says the following:
“Error verifying invite - Your invitation has been revoked. Please contact your workspace owner and ask them to resend it.”

**Comment by oscarholst** [comment]
Good point @Jacalz, the invite link may have expired. I will look into it. Thank you.

**Comment by Jacalz** [comment]
The link is still not working. Did you manage to find the solution? @oscarholst

**Comment by oscarholst** [comment]
> The link is still not working. Did you manage to find the solution? @oscarholst

Yes, my bad. Unfortunately this has not been a priority at the moment. The link had expired, but has now been updated. Thanks.

**Comment by Jacalz** [comment]
Thank you for getting it fixed. Is nice to be able to join the group now :)
